# Configure school-specific data
description = "This is a sample website for the ZASchools project. It is a proof-of-concept for a template-driven approach to building websites."
emisNo = "987654321"
physicalAddress = "897 Fry Street, Waverley"
town = "City of Tshwane"
province = "Gauteng"
phone = "012 987 6543"
email = "gerald@archton.io"
principal = "Gerald O'Sullivan"
location = "-25.697466360317964, 28.256089839890176"

# Configure Google Analytics
google_analytics_id = ""
google_tag_manager_id = ""

[homepage]
  show_contact_box = true
  show_services_button = true

[logo]
  mobile = "images/logo/dbe-logo.png"
  mobile_height = "36px"
  desktop = "images/logo/dbe-logo.png"
  desktop_height = "55px"
  alt = "Department of Basic Education Logo"

[fonts]
  google_fonts = "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap"
  heading = "Playfair Display"
  base = "Source Sans Pro"

[colors]
  primary = "#bf952a"
  black = "#2f2f41"
  white = "#ffffff"
  white_offset = "#f6f7ff"
  grey = "#5C5A5A"

[team]
  summary_large_truncate = 120

[theme]
  theme_text = 'Theme by <a href="https://www.archton.io">www.archton.io</a>'
